name: STAGING - Build and Deploy frontend

on:
  push:
    branches:
      - develop
    paths:
      - frontend/**
      - .github
env:
  GCP_PROJECT: "wedding-gift-planner"

jobs:
  deploy:
    name: Build and Deploy Staging Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "286.0.0"
          service_account_email: ${{ secrets.GCP_STAGING_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_STAGING_SA_KEY }}
          export_default_credentials: true
          project_id: ${{ env.GCP_PROJECT }}

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules-frontends
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('frontends/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Prepare for building frontend
        run: |
          cd frontend
          yarn install --frozen-lockfile
      - name: Build frontend
        run: |
          cd frontend
          yarn build
      - name: Deploy frontend
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:staging --project $GCP_PROJECT
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: frontend
