name: Deploy Web

on:
  push:
    branches:
      - develop
    paths-ignore:
      - api/**
      - .github/workflows/deploy-staging-api.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.NOW_TOKEN }}
          now-org-id: ${{ secrets.NOW_ORG_ID}}
          now-project-id: ${{ secrets.NOW_PROJECT_ID}}
          working-directory: ./web
