name: STAGING - Build and Deploy Web
on:
  push:
    branches:
      - develop
    paths-ignore:
      - api/**
      - .github/workflows/deploy-staging-api.yml
jobs:
  deploy:
    name: Build and Deploy Staging Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
